evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}

plug "andreyorst/plug.kak" noload

plug "catppuccin/kakoune" theme config %{
  colorscheme catppuccin_mocha
}

plug "andreyorst/fzf.kak" config %{
  map global normal <c-p> '<esc>: require-module fzf; require-module fzf-file; fzf-file; <ret>'
  map global user f ': fzf-mode<ret>' -docstring "FZF Mode"
} defer fzf-file %{
  set-option global fzf_file_command "rg -L --files "
}

map global user l ': enter-user-mode lsp<ret>' -docstring "LSP Mode"
map global user g ': terminal lazygit<ret>' -docstring "Lazygit"
map global user t ': terminal bash<ret>' -docstring "Terminal"
map global user n ': new<ret>' -docstring "New Window"
map global user w ': w<ret>' -docstring "Write"
map global user q ': q<ret>' -docstring "Quit"
map global normal <c-w> ': db<ret>'
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>'

hook global BufOpenFile .* %{
  editorconfig-load
  modeline-parse
}

hook global BufNewFile .* %{
  editorconfig-load
  modeline-parse
}

hook global BufWritePre .*[.]go %{
  try %{ lsp-code-actions-sync source.organizeImports }
  lsp-formatting-sync
}

set-option global windowing_modules 'x11'

eval %sh{kak-lsp}
lsp-enable
